sonar.projectKey=A01722757_ActInt1
sonar.projectName=TransmissionAutoCheck
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=cpp
sonar.sourceEncoding=UTF-8

sonar.cfamily.compile-commands=build/compile_commands.json
sonar.coverageReportPaths=build/coverage.xml

sonar.exclusions=main.cpp,test/**,build/**
sonar.coverage.exclusions=main.cpp,test/**,build/**
sonar.test=test
sonar.test.inclusions=test/**.cpp
